name: islamic_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter

# app dependencies
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  flutter_bloc: ^9.1.0
  flutter_localization: ^0.3.1
  animated_bottom_navigation_bar: ^1.4.0
  go_router: ^14.8.1
  equatable: ^2.0.7
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0
  bloc: ^9.0.0
  geolocator: ^13.0.3
  hijri: ^3.0.0
  http: ^1.3.0
 





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

#app assets
  assets:
     - assets/img/
     - assets/fonts/
     - assets/symbols/
     - assets/json_apis/
     - assets/sounds/
# app fonts
  fonts:
     - family: Cairo
       fonts:
         - asset: assets/fonts/cairo/Cairo-Regular.ttf
         - asset: assets/fonts/cairo/Cairo-Bold.ttf
         - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
         - asset: assets/fonts/cairo/Cairo-Light.ttf
         - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
         - asset: assets/fonts/cairo/Cairo-Black.ttf
           weight: 700
           style: italic
     - family: fares
       fonts:
         - asset: assets/fonts/fares/NotoNastaliqUrdu-Regular.ttf
         - asset: assets/fonts/fares/NotoNastaliqUrdu-Bold.ttf
         - asset: assets/fonts/fares/NotoNastaliqUrdu-Medium.ttf
         - asset: assets/fonts/fares/NotoNastaliqUrdu-SemiBold.ttf
           weight: 700
           style: italic


  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
